---
  Functional:
    - Пользователь должен иметь возможность искать товары по ключевому слову или категории
    - Пользователь должен иметь возможность фильтровать товары
    - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
    - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  non-functional:
    - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
    - Сайт должен быть безопасным и защищать данные пользователя
    - Сайт должен иметь мобильную версию
    - Сайт нужно протестировать на совместимость с последними версиями браузеров
    - Важно, чтобы сайт мог обрабатывать большое количество трафика
    - Сайт должен быть доступен на различных устройствах
    - Пользователь должен иметь возможность переключить язык интерфейса
    - Сайт должен иметь локализацию (перевод) на русский и английский языки
  implicit:
    - При первом посещении сайта отображается баннер, уведомляющий об использовании файлов coolie. В баннере указывается, что продолжая использовать сайт, пользователь соглашается на использование файлов cookie.
    - Gри переключении языка интерфейса во вкладке "Язык" обычно отображается флаг, соответствующий выбранному языку. 
